branch-defaults:
  master:
    environment: monolist-web-env
global:
  application_name: monolist-web
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git